version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.19.1
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm i -f
  build:
     commands:
      - chmod +x ./scripts/*.sh
      - echo npm run build
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/node_modules/**/*'
