
name: Deployment

on:
  push:
    branches: [development , master ]
jobs:
  
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: npm i -f

      - name: Buid the application
        run: npm run build

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Development
        if: github.ref == 'refs/heads/development'
        env:
          PRIVATE_KEY: ${{ secrets.LIFE_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.LIFE_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{secrets.LIFE_HOSTNAME}} '
            cd life_be &&
            sudo git fetch origin &&
            sudo git checkout development &&
            sudo git pull origin development &&
            npm i -f && NODE_OPTIONS="--max-old-space-size=1024" npm run build && npm run start:prod && pm2 save -f'
  
      - name: Deploy to Prod
        if: github.ref == 'refs/heads/master'
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOST_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -i private_key ubuntu@${{secrets.HOST_NAME}} '
            cd life_be &&
            sudo git fetch origin &&
            sudo git checkout master &&
            sudo git pull origin master &&
            npm i -f && NODE_OPTIONS="--max-old-space-size=1024" npm run build && npm run start:prod && pm2 save -f'

       
